name: CMake Test
on:
  push:
    paths:
      - ".github/workflows/build_test.yml"
      - "project/**"

jobs:
  build:
    name: ${{ matrix.os }}.CPP${{ matrix.version }}.${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    env:
      CPP_VERSION: ${{ matrix.version }})
      IS_DISABLE_EXCEPTION: ${{ matrix.disable_exception }})

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: ['Release', 'Debug']
        version: ["17", "20"]
        disable_exception: [TRUE, FALSE]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: create build environment
      run: cmake -E make_directory ${{ runner.workspace }}/_build

    # - name: Cache
    #   id: cache-primes
    #   uses: actions/cache@v2
    #   with:
    #     path: _build
    #     key: test--${{ matrix.os }}--CPP${{ matrix.version }}--${{ matrix.build_type }}--${{ matrix.disable_exception }}

    - name: configure cmake
      shell: bash
      working-directory: ${{ runner.workspace }}/_build
      run: cmake -DBENCHMARK_ENABLE_TESTING=OFF -DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON $GITHUB_WORKSPACE/project -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: build
      shell: bash
      working-directory: ${{ runner.workspace }}/_build
      run: cmake --build . --config ${{ matrix.build_type }}

    - name: Run tests
      shell: bash
      working-directory: ${{ runner.workspace }}/_build
      run: ctest -C ${{ matrix.build_type }}