name: CMake Benchmark
on:
  push:
    paths:
      - ".github/workflows/build_benchmark.yml"
      - "project/**"
env:
  IS_PERFORMANCE_TEST: TRUE

jobs:
  build:
    name: ${{ matrix.os }}.CPP${{ matrix.version }}
    runs-on: ${{ matrix.os }}
    env:
      CMAKE_C_COMPILER: ${{ matrix.cc }})
      CMAKE_CXX_COMPILER: ${{ matrix.cxx }})
      CPP_VERSION: ${{ matrix.version }})

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ["17", "20"]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: create build environment
      run: |
        cmake -E make_directory build
        cmake -E make_directory docs/Json

    - name: configure cmake
      shell: bash
      working-directory: build
      run: cmake -DBENCHMARK_ENABLE_TESTING=OFF -DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON ../project -DCMAKE_BUILD_TYPE=Release

    - name: build
      shell: bash
      working-directory: build
      run: cmake --build . --config Release

    - name: setup git
      shell: bash
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "actions"
        git fetch origin page
        git checkout page        

    - name: Run tests
      env:
        BENCHMARK_OUT: ../docs/Json/${{ matrix.os }}.CPP${{ matrix.version }}.json
        BENCHMARK_FORMAT: json    
      shell: bash
      working-directory: build
      run: ctest -C Release -V --parallel 1
      
    - uses: shogo82148/actions-mutex@v1
    - name: Commit files
      run: |
        git pull
        git add .
        git commit -m 'add benchmark result ${{ matrix.os }}.CPP${{ matrix.version }}' && git push origin page